####
POST https://backend-flutter.herokuapp.com/api/categories HTTP/1.1
content-type: application/json

{
    "name": "KFC",
    "description": "Nunca se es muy joven para comenzar, ni demasiado viejo para conquistar un sueño",
    "image": "https://drive.google.com/file/d/1wxz3KFr5D7FSQdLV2LFSHstvLnon6aii/view"
}
####

####
GET https://backend-flutter.herokuapp.com/api/categories HTTP/1.1

####

####
DELETE https://backend-flutter.herokuapp.com/api/categories/62acdd0cd72c2b9a0373d6d3 HTTP/1.1

####

####
GET https://backend-flutter.herokuapp.com/62acdd61d72c2b9a0373d6d7/products HTTP/1.1

####