#### CREAR CATEGORIA
POST https://backend-flutter.herokuapp.com/api/categories HTTP/1.1
content-type: application/json

{
    "name": "BURGER KING2",
    "description": "Di que eres Burger King Lover sin decir que eres Burger King Lover",
    "image": "https://res.cloudinary.com/dkyhpwmzf/image/upload/v1655501252/flutter_app/categories/burger-king-logo_rchxst.png"
}
####

#### LISTAR CATEGORIAS
GET https://backend-flutter.herokuapp.com/api/categories HTTP/1.1

####

#### ELIMINAR UNA CATEGORIA
DELETE https://backend-flutter.herokuapp.com/api/categories/62ad012718630f61ad9ddcb6 HTTP/1.1

####

#### LISTAR PRODUCTOS DE CATEGORIA
GET https://backend-flutter.herokuapp.com/api/categories/none-id/products HTTP/1.1

####