#### CREAR CATEGORIA
POST https://backend-flutter.herokuapp.com/api/categories HTTP/1.1
content-type: application/json

{
    "name": "Licores",
    "description": "Encontraras todo tipo de licores , desde el mas barato al mas caro  ",
    "image": "https://res.cloudinary.com/dkyhpwmzf/image/upload/v1655753853/flutter_app/categories/licores_mehaol.png"
}
####

#### LISTAR CATEGORIAS
GET https://backend-flutter.herokuapp.com/api/categories HTTP/1.1

####

#### ELIMINAR UNA CATEGORIA
DELETE https://backend-flutter.herokuapp.com/api/categories/62ad012718630f61ad9ddcb6 HTTP/1.1

####

#### LISTAR PRODUCTOS DE CATEGORIA
GET https://backend-flutter.herokuapp.com/api/categories/none-id/products HTTP/1.1

####