#### CREAR DELIVERY
POST https://backend-flutter.herokuapp.com/api/deliveries HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYTUxNzE3OTdhYzViYTBmOWU2Nzk2MiIsImlhdCI6MTY1NjcwOTE3OCwiZXhwIjoxNjU2Nzk1NTc4fQ.6a0OK6Blc_GgpF0auO_YkiGLEf3VcYg30UitrKyhoXk

{
    "identification": "Test 1",
    "address": "Calle falsa 123",
    "pin": "3245",
    "phone": "+51 946-123-4567",
    "date": "2020-01-01"
}
####

#### LISTAR DELIVERY
GET https://backend-flutter.herokuapp.com/api/deliveries HTTP/1.1

####

#### ELIMINAR DELIVERY
DELETE https://backend-flutter.herokuapp.com/api/deliveries/62ad019618630f61ad9ddcc0 HTTP/1.1

####