#### CREAR DELIVERY
POST https://backend-flutter.herokuapp.com/api/deliveries HTTP/1.1
content-type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYTUxNzE3OTdhYzViYTBmOWU2Nzk2MiIsImlhdCI6MTY1NzkxNzgzNywiZXhwIjoxNjU4MDA0MjM3fQ.74jFN1R4i4ZcsjzpLCQ0GmhnWAXO_rxBDjLbToCypvM

{
    "identification": "Test 2",
    "address": "Calle falsa 125",
    "pin": "3247",
    "phone": "+51 946-123-4567",
    "date": "2020-01-01"
}
####

#### LISTAR DELIVERY
GET https://backend-flutter.herokuapp.com/api/deliveries HTTP/1.1

####

#### ELIMINAR DELIVERY
DELETE https://backend-flutter.herokuapp.com/api/deliveries/62ad019618630f61ad9ddcc0 HTTP/1.1

####