#### CREAR PRODUCTO
POST https://backend-flutter.herokuapp.com/api/products HTTP/1.1
content-type: application/json

{
    "name": "LOWENBRAU",
    "price": "15  ",
    "description": "Cerveza de alta calidad , laburando desde hace mas de 20 años ",
    "image": "https://res.cloudinary.com/dkyhpwmzf/image/upload/v1655780537/flutter_app/products/mediebal_pt7lkd.png",
    "categoryId": "62b13454eb94af5e37ebf233"
}
####

#### LISTAR PRODUCTOS
GET https://backend-flutter.herokuapp.com/api/products HTTP/1.1

####

#### ELIMINAR PRODUCTO
DELETE https://backend-flutter.herokuapp.com/api/products/62ad019618630f61ad9ddcc0 HTTP/1.1

####