#### LOGIN
POST https://backend-flutter.herokuapp.com/api/auth/login HTTP/1.1
content-type: application/json

{
    "email": "test1@gmail.com",
    "password": "test1"
}
####


#### LISTAR USUARIOS
GET https://backend-flutter.herokuapp.com/api/users HTTP/1.1

####

#### ELIMINAR PRODUCTO
DELETE https://backend-flutter.herokuapp.com/api/users/62ad019618630f61ad9ddcc0 HTTP/1.1

####